### ISSUE TITLE
Feature : Add support for l18n and l10n

### ISSUE THREAD

**Issue by ShubhamHande99** [ShubhamHande99/flutter_I18n#2]
## Feature: Add support for l18n and l10n

**Description:**
Add support for l18n and l10n

**Tasks:**
- [x] Add support for l18n and l10n
- [x] make sure it support the following languages English, Hindi, Marathi and Arabic
- [x] make sure for language Arabic app support ltr to rtl
- [x] make sure app update all the language changes dynamically

**Comment by ShubhamHande99** [comment]
PR #4
